import React, { useState, useEffect, useMemo } from 'react'

// === i18n ===
const CATEGORIES_KO = ['전체','제휴마케팅','디지털상품','서비스대행','콘텐츠채널','드랍쉬핑','강의판매','자동화에이전시','AI코딩','AI영상','AI이미지','AI음악','AI문서','AI자동화','AI비즈니스','기타']
const CATEGORIES_EN = ['All','Affiliate','Digital Products','Service','Content Channel','Dropshipping','Course','Automation Agency','AI Coding','AI Video','AI Image','AI Music','AI Docs','AI Automation','AI Business','Other']

const UI = {
  ko: {
    siteTagline: "AI 수익화 영상 일간 랭킹",
    heroTitle: "AI로 돈 버는 영상,\n매일 자동 분석",
    heroSub: "YouTube에서 AI 수익화 관련 인기 영상을 자동 수집하고 분석합니다",
    regionKr: "🇰🇷 한국",
    regionGlobal: "🌍 글로벌",
    regionAitool: "🤖 AI Tool",
    tabShorts: "📱 쇼츠",
    tabVideos: "🎬 영상",
    tabDaily: "일간",
    tabWeekly: "주간",
    tabMonthly: "월간",
    search: "영상 제목, 채널명 검색...",
    noData: "데이터를 불러오는 중이거나 해당 조건의 영상이 없습니다.",
    watchVideo: "영상 보기",
    copyUrl: "URL 복사",
    copied: "복사됨!",
    method: "수익화 방법",
    principle: "핵심 원리",
    requirements: "필요한 것",
    difficulty: "난이도",
    cost: "초기비용",
    time: "수익까지",
    schedule: "매일 2회 자동 업데이트 (KST 07:00 / 19:00)",
    updated: "최근 업데이트",
    waiting: "업데이트 대기 중",
    disclaimer: "면책조항",
    disclaimerText: "본 사이트의 모든 정보는 AI가 자동 생성한 것으로, 투자 조언이 아닙니다. 모든 판단과 행동은 이용자 본인의 책임입니다.",
    source: "데이터 출처: YouTube Data API · 분석: OpenAI",
    masked: "채널명은 개인정보 보호를 위해 마스킹 처리됩니다",
    analyzeTitle: "영상 분석",
    analyzePlaceholder: "YouTube 영상 URL을 붙여넣으세요",
    analyzeBtn: "분석하기",
    analyzingText: "AI가 영상을 분석하고 있습니다",
    analyzeError: "분석에 실패했습니다. URL을 확인해주세요.",
    analyzeDisclaimer: "본 분석은 AI 시스템이 공개된 메타데이터를 기반으로 자동 생성한 구조적 의견이며, 특정 개인이나 채널에 대한 주관적 평가가 아닙니다.",
    revenuePotential: "수익 잠재력",
    competition: "경쟁 강도",
    reproducibility: "재현 가능성",
    growthOutlook: "성장 전망",
    keyInsight: "핵심 인사이트",
    actionRoadmap: "실행 로드맵",
    revenueScore: "수익 점수",
    aiRelevance: "AI 관련도",
    contactTitle: "문의하기",
    contactName: "이름",
    contactEmail: "이메일",
    contactMessage: "내용",
    contactSend: "보내기",
    contactSent: "전송 완료! 빠르게 답변드리겠습니다.",
    contactTypes: ["일반 문의","광고 문의","삭제 요청","버그 제보","기타"],
    termsTitle: "이용약관",
    aboutTitle: "이 사이트는?",
    aboutText: "FeedScan AI는 매일 YouTube에서 AI 수익화 관련 인기 콘텐츠를 자동 수집·분석하여 랭킹으로 정리합니다.",
    rankTitle: "랭킹 기준",
    rankRules: ["일간: 최근 7일 내 업로드, 조회수 순","주간: 7일간 누적 등장 × 조회수","월간: 30일간 누적 등장 × 조회수"],
    reportBtn: "삭제 요청",
    adSlotEmpty: "광고 문의",
    shareText: "공유",
    likeText: "추천",
    filterTitle: "필터",
    filterHint: "레벨 클릭 시 해당 수준 이하만 표시",
  },
  en: {
    siteTagline: "AI Monetization Video Daily Ranking",
    heroTitle: "AI Money-Making Videos,\nAnalyzed Daily",
    heroSub: "Auto-collecting and analyzing popular AI monetization videos from YouTube",
    regionKr: "🇰🇷 Korea",
    regionGlobal: "🌍 Global",
    regionAitool: "🤖 AI Tool",
    tabShorts: "📱 Shorts",
    tabVideos: "🎬 Videos",
    tabDaily: "Daily",
    tabWeekly: "Weekly",
    tabMonthly: "Monthly",
    search: "Search by title, channel...",
    noData: "Loading data or no videos match the criteria.",
    watchVideo: "Watch",
    copyUrl: "Copy URL",
    copied: "Copied!",
    method: "Monetization Method",
    principle: "Core Principle",
    requirements: "Requirements",
    difficulty: "Difficulty",
    cost: "Initial Cost",
    time: "Time to Profit",
    schedule: "Auto-updated 2x daily (KST 07:00 / 19:00)",
    updated: "Last updated",
    waiting: "Waiting for update",
    disclaimer: "Disclaimer",
    disclaimerText: "All information on this site is AI-generated and does not constitute investment advice. All decisions and actions are the user's own responsibility.",
    source: "Data: YouTube Data API · Analysis: OpenAI",
    masked: "Channel names are masked for privacy",
    analyzeTitle: "Analyze Video",
    analyzePlaceholder: "Paste a YouTube video URL here",
    analyzeBtn: "Analyze",
    analyzingText: "AI is analyzing the video",
    analyzeError: "Analysis failed. Please check the URL.",
    analyzeDisclaimer: "This analysis is automatically generated by an AI system based on public metadata. It is not a subjective evaluation of any individual or channel.",
    revenuePotential: "Revenue Potential",
    competition: "Competition",
    reproducibility: "Reproducibility",
    growthOutlook: "Growth Outlook",
    keyInsight: "Key Insight",
    actionRoadmap: "Action Roadmap",
    revenueScore: "Revenue Score",
    aiRelevance: "AI Relevance",
    contactTitle: "Contact",
    contactName: "Name",
    contactEmail: "Email",
    contactMessage: "Message",
    contactSend: "Send",
    contactSent: "Sent! We'll get back to you soon.",
    contactTypes: ["General","Advertising","Removal Request","Bug Report","Other"],
    termsTitle: "Terms of Service",
    aboutTitle: "About",
    aboutText: "FeedScan AI automatically collects and analyzes popular AI monetization content from YouTube daily, organizing them into rankings.",
    rankTitle: "Ranking Criteria",
    rankRules: ["Daily: Uploaded within 7 days, sorted by views","Weekly: 7-day appearance count × views","Monthly: 30-day appearance count × views"],
    reportBtn: "Request Removal",
    adSlotEmpty: "Advertise here",
    shareText: "Share",
    likeText: "Upvote",
    filterTitle: "Filter",
    filterHint: "Click a level to show only items at or below that level",
  }
}

// === COMPONENTS ===
function MeterBar({value, color}) {
  return (<div className="flex gap-0.5">{Array.from({length:5},(_,i)=>(<div key={i} className={`h-2.5 w-5 rounded-sm ${i<value?color:'bg-slate-700'}`}/>))}</div>)
}

function ClickableMeter({label, value, onChange, color}) {
  return (<div className="flex items-center gap-2"><span className="w-16 text-slate-400 text-xs shrink-0">{label}</span><div className="flex gap-0.5">{Array.from({length:5},(_,i)=>(<button key={i} onClick={()=>onChange(value===i+1?null:i+1)} className={`h-3 w-5 rounded-sm transition-all ${i<(value||0)?color:'bg-slate-700'} hover:opacity-80`}/>))}</div></div>)
}

function formatViews(n) {
  if (!n) return '0'
  if (n >= 1000000) return (n/1000000).toFixed(1) + 'M'
  if (n >= 1000) return (n/1000).toFixed(1) + 'K'
  return n.toString()
}

// Product Hunt style rank item
function RankItem({item, rank, lang, t, isExpanded, onToggle, onWatch, isDark, ads}) {
  const title = lang==='ko' ? (item.title_ko||item.title) : (item.title_en||item.title)
  const subtitle = lang==='ko' ? (item.title_en||'') : (item.title_ko||'')
  const method = lang==='ko' ? (item.method||'') : (item.method_en||item.method||'')
  const [liked, setLiked] = useState(false)
  const [copyFeedback, setCopyFeedback] = useState(false)

  const handleLike = (e) => {
    e.stopPropagation()
    setLiked(!liked)
    // localStorage에 저장
    const key = `like_${item.video_id}`
    if (!liked) { localStorage.setItem(key, '1') } else { localStorage.removeItem(key) }
  }

  const handleCopy = (e) => {
    e.stopPropagation()
    const url = item.is_short !== false
      ? `https://www.youtube.com/shorts/${item.video_id}`
      : `https://www.youtube.com/watch?v=${item.video_id}`
    navigator.clipboard.writeText(url)
    setCopyFeedback(true)
    setTimeout(() => setCopyFeedback(false), 2000)
  }

  const handleShare = (e) => {
    e.stopPropagation()
    const url = item.is_short !== false
      ? `https://www.youtube.com/shorts/${item.video_id}`
      : `https://www.youtube.com/watch?v=${item.video_id}`
    const text = `${title} - FeedScan AI`
    if (navigator.share) {
      navigator.share({ title: text, url })
    } else {
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`, '_blank')
    }
  }

  // 좋아요 초기 상태
  useEffect(() => {
    const key = `like_${item.video_id}`
    if (localStorage.getItem(key)) setLiked(true)
  }, [item.video_id])

  return (
    <div className={`rounded-xl overflow-hidden transition-all w-full max-w-full ${isDark?'bg-slate-900/60 border border-slate-800 hover:border-slate-600':'bg-white border border-gray-200 hover:border-gray-400 shadow-sm'}`}>
      {/* Main row - PH style */}
      <div className="flex items-center gap-3 p-4 cursor-pointer" onClick={onToggle}>
        {/* Rank number */}
        <span className="text-slate-500 font-bold text-lg w-8 text-center shrink-0">{rank}</span>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <h3 className={`font-medium text-sm leading-tight truncate ${isDark?'text-white':'text-gray-900'}`}>{title}</h3>
          {method && <p className={`text-xs mt-1 truncate ${isDark?'text-slate-400':'text-gray-500'}`}>{method}</p>}
          <div className="flex items-center gap-2 mt-1.5 flex-wrap">
            <span className="text-slate-500 text-xs">👁 {formatViews(item.views)}</span>
            <span className="text-slate-500 text-xs">♥ {formatViews(item.likes)}</span>
            <span className={`px-1.5 py-0.5 rounded text-[10px] ${item.language==='ko'?'bg-blue-900/50 text-blue-300':'bg-emerald-900/50 text-emerald-300'}`}>{item.language==='ko'?'KR':'EN'}</span>
            {item.is_new && <span className="px-1.5 py-0.5 rounded bg-red-900/50 text-red-300 text-[10px] animate-pulse">NEW</span>}
          </div>
        </div>

        {/* Right side - Upvote button (PH style) */}
        <button onClick={handleLike} className={`flex flex-col items-center px-3 py-2 rounded-lg border transition-all shrink-0 ${liked?'border-indigo-500 bg-indigo-900/30 text-indigo-300':isDark?'border-slate-700 bg-slate-800 text-slate-400 hover:border-slate-500':'border-gray-300 bg-gray-100 text-gray-500 hover:border-gray-400'}`}>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7"/></svg>
          <span className="text-xs font-medium mt-0.5">{formatViews(item.views)}</span>
        </button>
      </div>

      {/* Expanded detail */}
      {isExpanded && (
        <div className={`border-t p-4 space-y-4 ${isDark?'border-slate-800 bg-slate-950/50':'border-gray-100 bg-gray-50'}`}>
          {subtitle && <p className={`text-xs ${isDark?'text-slate-400':'text-gray-500'}`}>{subtitle}</p>}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div className={`rounded-lg p-3 ${isDark?'bg-slate-800/50':'bg-white border border-gray-200'}`}>
              <h4 className="text-indigo-500 text-xs font-medium mb-1">{t.method}</h4>
              <p className={`text-sm ${isDark?'text-white':'text-gray-800'}`}>{lang==='ko'?(item.method||''):(item.method_en||item.method||'')}</p>
            </div>
            <div className={`rounded-lg p-3 ${isDark?'bg-slate-800/50':'bg-white border border-gray-200'}`}>
              <h4 className="text-indigo-500 text-xs font-medium mb-1">{t.principle}</h4>
              <p className={`text-sm ${isDark?'text-white':'text-gray-800'}`}>{lang==='ko'?(item.principle||''):(item.principle_en||item.principle||'')}</p>
            </div>
          </div>
          <div className={`rounded-lg p-3 ${isDark?'bg-slate-800/50':'bg-white border border-gray-200'}`}>
            <h4 className="text-indigo-500 text-xs font-medium mb-1">{t.requirements}</h4>
            <p className={`text-sm ${isDark?'text-white':'text-gray-800'}`}>{lang==='ko'?(item.requirements||''):(item.requirements_en||item.requirements||'')}</p>
          </div>
          <div className="flex flex-wrap gap-6">
            <div><span className="text-slate-400 text-xs block mb-1">{t.difficulty}</span><MeterBar value={item.difficulty} color="bg-orange-500"/></div>
            <div><span className="text-slate-400 text-xs block mb-1">{t.cost}</span><MeterBar value={item.initial_cost} color="bg-red-500"/></div>
            <div><span className="text-slate-400 text-xs block mb-1">{t.time}</span><MeterBar value={item.time_to_profit} color="bg-yellow-500"/></div>
          </div>
          {/* Action buttons */}
          <div className="flex gap-2 flex-wrap">
            <button onClick={(e)=>{e.stopPropagation();onWatch(item.video_id)}} className="inline-flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-500 text-white text-sm rounded-lg transition-colors">
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor"><path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814z"/><path fill="#fff" d="M9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>
              {t.watchVideo}
            </button>
            <button onClick={handleCopy} className="inline-flex items-center gap-1 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white text-sm rounded-lg transition-colors">
              {copyFeedback ? `✅ ${t.copied}` : `📋 ${t.copyUrl}`}
            </button>
          </div>
          {/* Random ad */}
          {ads&&ads.length>0&&(()=>{const ad=ads[Math.floor(Math.random()*ads.length)];const adTitle=lang==='en'?(ad.title_en||ad.title):ad.title;const adDesc=lang==='en'?(ad.description_en||ad.description):ad.description;return ad.url?(<a href={ad.url} target="_blank" rel="noopener noreferrer nofollow" className={`block mt-3 rounded-lg p-3 border transition-all ${isDark?'bg-indigo-900/10 border-indigo-500/20 hover:border-indigo-400/40':'bg-indigo-50 border-indigo-200 hover:border-indigo-400'}`}><div className="flex items-center gap-3"><span className="text-[9px] text-indigo-400 font-bold uppercase">AD</span><span className={`text-sm font-medium ${isDark?'text-white':'text-gray-800'}`}>{adTitle}</span><span className={`text-xs ml-auto ${isDark?'text-slate-400':'text-gray-500'}`}>{adDesc}</span></div></a>):null})()}
        </div>
      )}
    </div>
  )
}

function AdAsRank({ad, lang}){ if(!ad) return null; const title=lang==='en'?(ad.title_en||ad.title):ad.title; const desc=lang==='en'?(ad.description_en||ad.description):ad.description; return (<a href={ad.url} target="_blank" rel="noopener noreferrer nofollow" className="block bg-gradient-to-r from-indigo-900/20 to-purple-900/20 border border-indigo-500/20 rounded-xl p-4 hover:border-indigo-400/40 transition-all"><div className="flex items-start gap-4"><span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-indigo-600/50 text-indigo-200 font-bold text-[10px] flex-shrink-0">AD</span><div className="flex-1 min-w-0"><h3 className="text-white font-medium text-sm truncate">{title}</h3><p className="text-slate-400 text-xs mt-1 truncate">{desc}</p></div><span className="text-indigo-400 text-xs whitespace-nowrap self-center">{lang==='en'?'Visit →':'바로가기 →'}</span></div></a>) }

function SidebarAdSlot({ad, lang, t}){ if(!ad) return (<div className="border border-dashed border-slate-700 rounded-lg p-2 text-center"><p className="text-slate-600 text-[10px]">{t.adSlotEmpty}</p></div>); const title=lang==='en'?(ad.title_en||ad.title):ad.title; const desc=lang==='en'?(ad.description_en||ad.description):ad.description; const cta=lang==='en'?(ad.cta_en||'Learn more →'):(ad.cta||'자세히 보기 →'); return (<a href={ad.url} target="_blank" rel="noopener noreferrer nofollow" className="block bg-gradient-to-r from-indigo-900/30 to-purple-900/30 border border-indigo-500/30 rounded-lg p-2.5 hover:border-indigo-400/50 transition-all"><span className="text-[9px] text-slate-500 uppercase">AD</span><h4 className="text-white font-medium text-xs mt-0.5">{title}</h4><p className="text-slate-400 text-[10px] mt-0.5 leading-tight">{desc}</p><span className="inline-block mt-1 text-[10px] text-indigo-400">{cta}</span></a>) }

function TrendKeywords({data}){
  const keywords = useMemo(()=>{
    if(!data) return []; const allItems=[...(data.shorts_top10||[]),...(data.videos_top10||[]),...(data.top10||[])]; const wordMap={}
    const stopwords=new Set(['the','to','with','a','an','and','or','how','make','money','ai','in','for','from','your','this','that','is','are','was','were','be','been','have','has','had','do','does','did','will','can','could','would','should','may','might','i','you','he','she','it','we','they','my','our','its','his','her','their','of','on','at','by','up','out','about','into','over','after','per','day','using'])
    allItems.forEach(item=>{ const text=`${item.title} ${item.title_en||''} ${item.method_en||''}`; const words=text.toLowerCase().replace(/[^a-z가-힣0-9\s]/g,' ').split(/\s+/); words.forEach(w=>{ if(w.length<3||stopwords.has(w)||/^\d+$/.test(w)) return; wordMap[w]=(wordMap[w]||0)+1 }) })
    return Object.entries(wordMap).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([word,count])=>({word,count}))
  },[data])
  if(keywords.length===0) return null; const maxCount=keywords[0]?.count||1
  const colors=['text-indigo-300','text-purple-300','text-cyan-300','text-emerald-300','text-amber-300','text-rose-300']
  return (<div className="flex flex-wrap gap-2">{keywords.map((kw,i)=>{const size=kw.count/maxCount;const fontSize=size>0.7?'text-sm font-bold':size>0.4?'text-xs font-medium':'text-xs';return(<span key={kw.word} className={`${fontSize} ${colors[i%colors.length]} bg-slate-800/80 px-2 py-0.5 rounded-full border border-slate-700`}>{kw.word}</span>)})}</div>)
}

// === MAIN APP ===
export default function App(){
  const [lang, setLang] = useState(()=>{ if(typeof navigator!=='undefined'&&navigator.language.startsWith('ko')) return 'ko'; return 'en' })
  const t = UI[lang]
  const [dailyData, setDailyData] = useState(null)
  const [weeklyData, setWeeklyData] = useState(null)
  const [monthlyData, setMonthlyData] = useState(null)
  const [adsConfig, setAdsConfig] = useState(null)
  const [visitorCount, setVisitorCount] = useState(null)
  const [region, setRegion] = useState('global')
  const [contentType, setContentType] = useState('shorts')
  const [period, setPeriod] = useState('daily')
  const [searchQuery, setSearchQuery] = useState('')
  const [activeCategory, setActiveCategory] = useState('전체')
  const [expandedId, setExpandedId] = useState(null)
  const [filterDifficulty, setFilterDifficulty] = useState(null)
  const [filterCost, setFilterCost] = useState(null)
  const [filterTime, setFilterTime] = useState(null)
  const [popupVideoId, setPopupVideoId] = useState(null)
  const [showAnalyzer, setShowAnalyzer] = useState(true)
  const [theme, setTheme] = useState(()=>localStorage.getItem('theme')||'dark')
  const [analyzeUrl, setAnalyzeUrl] = useState('')
  const [analyzeResult, setAnalyzeResult] = useState(null)
  const [analyzeLoading, setAnalyzeLoading] = useState(false)
  const [analyzeError, setAnalyzeError] = useState('')
  const [showContact, setShowContact] = useState(false)
  const [contactSent, setContactSent] = useState(false)
  const [showTerms, setShowTerms] = useState(false)
  const isDark = theme === 'dark'

  useEffect(()=>{
    document.documentElement.classList.toggle('dark', isDark)
    localStorage.setItem('theme', theme)
  },[theme, isDark])

  const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbwCI2lXGZtByYz23QXZHVfgoHKT6RvqE1l1jkPQtV2pVSr4oB-ijoojJrWcyJXhKcx6/exec'
  useEffect(()=>{
    loadLatestDaily()
    // 구글 시트에서 광고 로드
    fetch(SCRIPT_URL+'?action=ads').then(r=>r.ok?r.json():null).then(data=>{
      if(data&&Array.isArray(data)){
        const ads=data.map(d=>({
          id:d.id,
          title:d.hook,
          title_en:d.hook,
          description:d.desc,
          description_en:d.desc,
          url:d.url,
          cta:'바로가기 →',
          cta_en:'Visit →',
          position:d.shot==='sidebar'?'sidebar':d.shot==='inline'?'inline':'banner',
          active:true
        }))
        setAdsConfig({ads})
      }
    }).catch(()=>fetch('/config/ads.json').then(r=>r.ok?r.json():null).then(setAdsConfig).catch(()=>{}))
    // 방문자 기록
    fetch(SCRIPT_URL+'?action=visit').then(r=>r.ok?r.json():null).then(d=>{if(d)setVisitorCount(d.total)}).catch(()=>{})
  },[])
  useEffect(()=>{
    const suffix = contentType === 'shorts' ? '_shorts' : '_videos'
    const prefix = region==='korea'?'_kr':region==='aitool'?'_aitool':''
    fetch(`/data/weekly${prefix}${suffix}.json`).then(r=>r.ok?r.json():null).then(setWeeklyData).catch(()=>setWeeklyData(null))
    fetch(`/data/monthly${prefix}${suffix}.json`).then(r=>r.ok?r.json():null).then(setMonthlyData).catch(()=>setMonthlyData(null))
  },[contentType, region])

  async function loadLatestDaily(){ const today=new Date(); for(let i=0;i<7;i++){const d=new Date(today);d.setDate(d.getDate()-i);const ds=d.toISOString().split('T')[0];try{const r=await fetch(`/data/daily/${ds}.json`);if(r.ok){setDailyData(await r.json());return}}catch(e){}} }

  async function handleAnalyze(){
    if(!analyzeUrl.trim()) return; setAnalyzeLoading(true); setAnalyzeError(''); setAnalyzeResult(null)
    try{
      const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:analyzeUrl})})
      if(!res.ok){const err=await res.json();throw new Error(err.error||'Failed')}
      setAnalyzeResult(await res.json())
    }catch(e){setAnalyzeError(t.analyzeError)}
    finally{setAnalyzeLoading(false)}
  }

  function getDisplayData(){ let data=[]; if(period==='daily'){ let key; if(region==='korea') key=contentType==='shorts'?'kr_shorts_top10':'kr_videos_top10'; else if(region==='aitool') key=contentType==='shorts'?'aitool_shorts_top10':'aitool_videos_top10'; else key=contentType==='shorts'?'shorts_top10':'videos_top10'; data=dailyData?.[key]||[]; if(data.length===0) data=dailyData?.top10||[] } else if(period==='weekly') data=weeklyData?.top5||[]; else if(period==='monthly') data=monthlyData?.top5||[]; return data }
  function getFilteredData(){ let data=getDisplayData(); if(activeCategory!=='전체') data=data.filter(i=>i.category===activeCategory); if(searchQuery.trim()){const q=searchQuery.toLowerCase();data=data.filter(i=>i.title.toLowerCase().includes(q)||(i.title_ko||'').toLowerCase().includes(q)||(i.title_en||'').toLowerCase().includes(q)||i.channel_masked.toLowerCase().includes(q))} if(filterDifficulty) data=data.filter(i=>i.difficulty<=filterDifficulty); if(filterCost) data=data.filter(i=>i.initial_cost<=filterCost); if(filterTime) data=data.filter(i=>i.time_to_profit<=filterTime); return data }

  const bannerAd=adsConfig?.ads?.find(a=>a.position==='banner'&&a.active)
  const inlineAd=adsConfig?.ads?.find(a=>a.position==='inline'&&a.active)
  const sidebarAds=adsConfig?.ads?.filter(a=>a.position==='sidebar'&&a.active)||[]
  const items=getFilteredData()
  const categories=lang==='ko'?CATEGORIES_KO:CATEGORIES_EN
  const categoryKeys=CATEGORIES_KO
  const hasFilters=filterDifficulty||filterCost||filterTime
  const popupAd=bannerAd||inlineAd

  function formatUpdateTime(){ if(!dailyData?.scanned_at) return t.waiting; const d=new Date(dailyData.scanned_at); if(lang==='ko') return `${d.getMonth()+1}/${d.getDate()} ${d.getHours().toString().padStart(2,'0')}:${d.getMinutes().toString().padStart(2,'0')}`; return `${d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}` }

  return (
    <div className={`min-h-screen overflow-x-hidden ${isDark?'bg-[#0f0f1a] text-white':'bg-gray-50 text-gray-900'}`}>
      {/* Video Popup */}
      {popupVideoId&&(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm" onClick={()=>setPopupVideoId(null)}><div className="relative w-full max-w-sm mx-4" onClick={e=>e.stopPropagation()}><button onClick={()=>setPopupVideoId(null)} className="absolute -top-10 right-0 text-white text-2xl hover:text-red-400">&times;</button><div className="rounded-xl overflow-hidden bg-black shadow-2xl"><iframe src={`https://www.youtube.com/embed/${popupVideoId}?autoplay=1&loop=1`} className="w-full aspect-[9/16]" allow="autoplay; encrypted-media" allowFullScreen title="YouTube Shorts"/></div><a href={`https://www.youtube.com/shorts/${popupVideoId}`} target="_blank" rel="noopener noreferrer" className="block mt-2 text-center text-indigo-400 text-xs hover:text-indigo-300">{lang==='ko'?'YouTube에서 직접 보기 →':'Open in YouTube →'}</a>{popupAd&&(<a href={popupAd.url} target="_blank" rel="noopener noreferrer nofollow" className="block mt-2 bg-gradient-to-r from-indigo-900/40 to-purple-900/40 border border-indigo-500/30 rounded-lg p-3 text-center hover:border-indigo-400/60 transition-all"><p className="text-white text-sm font-medium">{lang==='en'?(popupAd.title_en||popupAd.title):popupAd.title}</p><p className="text-slate-400 text-xs mt-1">{lang==='en'?(popupAd.description_en||popupAd.description):popupAd.description}</p></a>)}</div></div>)}

      {/* Contact Modal */}
      {showContact&&(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm" onClick={()=>{setShowContact(false);setContactSent(false)}}><div className="bg-slate-900 border border-slate-700 rounded-xl p-6 w-full max-w-md mx-4" onClick={e=>e.stopPropagation()}><h3 className="text-white font-bold text-lg mb-4">{t.contactTitle}</h3>{contactSent?(<p className="text-emerald-400 text-sm">{t.contactSent}</p>):(<form action="https://formspree.io/f/xyeggkzq" method="POST" onSubmit={()=>setTimeout(()=>setContactSent(true),500)}><div className="space-y-3"><input name="name" required placeholder={t.contactName} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white placeholder-slate-500"/><input name="email" type="email" required placeholder={t.contactEmail} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white placeholder-slate-500"/><select name="type" className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white">{t.contactTypes.map(ct=>(<option key={ct} value={ct}>{ct}</option>))}</select><textarea name="message" required rows={4} placeholder={t.contactMessage} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white placeholder-slate-500"/><button type="submit" className="w-full bg-indigo-600 hover:bg-indigo-500 text-white py-2 rounded-lg text-sm font-medium">{t.contactSend}</button></div></form>)}<button onClick={()=>{setShowContact(false);setContactSent(false)}} className="mt-4 text-slate-400 text-xs hover:text-white">닫기 / Close</button></div></div>)}

      {/* Terms Modal */}
      {showTerms&&(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm overflow-y-auto" onClick={()=>setShowTerms(false)}><div className="bg-slate-900 border border-slate-700 rounded-xl p-6 w-full max-w-lg mx-4 my-8 max-h-[80vh] overflow-y-auto" onClick={e=>e.stopPropagation()}><h3 className="text-white font-bold text-lg mb-4">{t.termsTitle}</h3><div className="text-slate-300 text-xs space-y-3 leading-relaxed"><p><strong>1. 서비스 목적 / Purpose</strong><br/>FeedScan AI는 공개된 YouTube 메타데이터를 자동 수집·분석하여 정보를 제공하는 도구입니다. 투자 자문, 수익 보장, 특정 행동 권유의 목적이 아닙니다.</p><p><strong>2. 면책 / Disclaimer</strong><br/>본 사이트에 표시된 정보는 AI가 자동 생성한 것으로, 정확성·완전성·최신성을 보장하지 않습니다. 이용자의 판단과 행동에 대한 책임은 전적으로 이용자 본인에게 있습니다.</p><p><strong>3. 저작권 / Copyright</strong><br/>본 사이트는 YouTube의 공식 임베드 기능과 공개 API만을 사용합니다. 콘텐츠 제작자의 권리를 존중하며, 삭제 요청 시 즉시 대응합니다.</p><p><strong>4. 채널명 마스킹 / Channel Masking</strong><br/>모든 채널명은 개인정보 보호를 위해 일부 마스킹 처리됩니다.</p><p><strong>5. 삭제 요청 / Removal Request</strong><br/>본인의 콘텐츠가 표시되는 것을 원하지 않는 경우, 문의 폼을 통해 삭제를 요청할 수 있습니다.</p><p><strong>6. 광고 / Advertising</strong><br/>본 사이트에는 제휴 광고가 포함되어 있습니다. 광고 클릭 시 외부 사이트로 이동하며, 해당 사이트의 내용은 FeedScan AI와 무관합니다.</p></div><button onClick={()=>setShowTerms(false)} className="mt-4 text-indigo-400 text-sm hover:text-white">닫기 / Close</button></div></div>)}

      {/* Header */}
      <header className={`border-b sticky top-0 z-50 backdrop-blur-sm ${isDark?'border-slate-800/50 bg-[#0f0f1a]/90':'border-gray-200 bg-white/90'}`}>
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <h1 className="text-lg font-bold cursor-pointer" onClick={()=>window.location.reload()}><span className="text-indigo-500">Feed</span>Scan AI</h1>
            <span className={`hidden md:inline text-xs border-l pl-3 ${isDark?'text-slate-500 border-slate-700':'text-gray-500 border-gray-300'}`}>{t.siteTagline}</span>
            {visitorCount&&<span className={`hidden md:inline text-xs border-l pl-3 ${isDark?'text-slate-500 border-slate-700':'text-gray-500 border-gray-300'}`}>👥 {visitorCount.toLocaleString()}</span>}
          </div>
          <div className="flex items-center gap-2">
            <span className="hidden md:inline text-yellow-500 font-medium text-xs">{formatUpdateTime()}</span>
            <button onClick={()=>{const url=window.location.href;const text=lang==='ko'?'AI 수익화 영상 일간 랭킹 - FeedScan AI':'AI Monetization Video Daily Ranking - FeedScan AI';if(navigator.share){navigator.share({title:text,url})}else{navigator.clipboard.writeText(url);alert(lang==='ko'?'링크가 복사되었습니다!':'Link copied!')}}} className={`px-2.5 py-1 rounded border text-xs transition-colors ${isDark?'border-slate-700 text-slate-400 hover:bg-slate-800':'border-gray-300 text-gray-600 hover:bg-gray-100'}`}>{lang==='ko'?'🔗 공유':'🔗 Share'}</button>
            <button onClick={()=>setTheme(isDark?'light':'dark')} className={`px-2.5 py-1 rounded border text-xs transition-colors ${isDark?'border-slate-700 text-slate-400 hover:bg-slate-800':'border-gray-300 text-gray-600 hover:bg-gray-100'}`}>{isDark?'☀️':'🌙'}</button>
            <button onClick={()=>setShowContact(true)} className={`hidden md:inline px-2.5 py-1 rounded border text-xs transition-colors ${isDark?'border-slate-700 text-slate-400 hover:bg-slate-800':'border-gray-300 text-gray-600 hover:bg-gray-100'}`}>{t.contactTitle}</button>
            <button onClick={()=>setLang(lang==='ko'?'en':'ko')} className={`px-2.5 py-1 rounded border text-xs font-medium transition-colors ${isDark?'border-slate-700 text-slate-400 hover:bg-slate-800':'border-gray-300 text-gray-600 hover:bg-gray-100'}`}>{lang==='ko'?'EN':'한국어'}</button>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-6 overflow-hidden">
        {/* Hero section - mobile first impression */}
        <div className="text-center mb-6 py-4 px-2">
          <h2 className={`text-xl sm:text-2xl md:text-3xl font-bold leading-tight break-keep ${isDark?'text-white':'text-gray-900'}`}>{t.heroTitle}</h2>
          <p className={`text-xs sm:text-sm mt-2 break-keep ${isDark?'text-slate-400':'text-gray-500'}`}>{t.heroSub}</p>
          <p className="text-yellow-500 font-semibold text-[11px] sm:text-xs mt-3 break-keep">{t.schedule}</p>
        </div>

        {/* URL Analyzer - Always visible */}
        <div className={`border rounded-xl mb-6 overflow-hidden ${isDark?'bg-gradient-to-r from-indigo-900/10 to-purple-900/10 border-indigo-500/20':'bg-indigo-50 border-indigo-200'}`}>
          <div className="p-3 flex items-center justify-between">
            <span className={`font-medium text-sm ${isDark?'text-indigo-300':'text-indigo-600'}`}>{t.analyzeTitle} — {lang==='ko'?'YouTube 영상의 수익 구조를 분석해보세요':'Analyze the revenue structure of any YouTube video'}</span>
          </div>
          <div className="px-4 pb-4">
            <div className="flex gap-2">
              <input type="text" value={analyzeUrl} onChange={e=>setAnalyzeUrl(e.target.value)} placeholder={t.analyzePlaceholder} className={`flex-1 rounded-lg px-4 py-2 text-sm focus:outline-none focus:border-indigo-500 ${isDark?'bg-slate-800 border border-slate-700 text-white placeholder-slate-500':'bg-white border border-gray-300 text-gray-900 placeholder-gray-400'}`} onKeyDown={e=>{if(e.key==='Enter')handleAnalyze()}}/>
              <button onClick={handleAnalyze} disabled={analyzeLoading} className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-slate-700 text-white text-sm rounded-lg transition-colors whitespace-nowrap">
                {analyzeLoading?(<span className="inline-flex items-center gap-2"><svg className="animate-spin h-4 w-4" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg><span className="hidden sm:inline">{t.analyzingText}</span><span className="sm:hidden">...</span></span>):t.analyzeBtn}
              </button>
            </div>
            {analyzeError&&<p className="text-red-400 text-xs mt-2">{analyzeError}</p>}
            {analyzeLoading&&<div className="mt-3 flex items-center gap-3"><div className="flex gap-1"><div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{animationDelay:'0ms'}}/><div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{animationDelay:'150ms'}}/><div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce" style={{animationDelay:'300ms'}}/></div><span className="text-indigo-300 text-xs">{t.analyzingText}...</span></div>}
            {analyzeResult&&(
              <div className="mt-4 bg-slate-900/50 border border-slate-700 rounded-lg p-4 space-y-4">
                <div className="flex items-center justify-between flex-wrap gap-2"><h3 className="text-white font-bold text-base">{lang==='ko'?(analyzeResult.title_ko||analyzeResult.title):(analyzeResult.title_en||analyzeResult.title)}</h3><span className={`px-2 py-0.5 rounded text-xs ${analyzeResult.ai_relevance==='높음'||analyzeResult.ai_relevance_en==='High'?'bg-emerald-900/50 text-emerald-300 border border-emerald-700':'bg-yellow-900/50 text-yellow-300 border border-yellow-700'}`}>{t.aiRelevance}: {lang==='ko'?analyzeResult.ai_relevance:analyzeResult.ai_relevance_en}</span></div>
                <div className="bg-indigo-900/30 border border-indigo-500/30 rounded-lg p-3"><p className="text-indigo-200 text-sm font-medium">{lang==='ko'?analyzeResult.verdict:analyzeResult.verdict_en}</p></div>
                <div className="flex items-center gap-3"><span className="text-slate-400 text-xs">{t.revenueScore}</span><div className="flex gap-0.5">{Array.from({length:10},(_,i)=>(<div key={i} className={`h-3 w-4 rounded-sm ${i<analyzeResult.revenue_score?'bg-emerald-500':'bg-slate-700'}`}/>))}</div><span className="text-emerald-400 text-sm font-bold">{analyzeResult.revenue_score}/10</span></div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                  <div className="bg-slate-800/50 rounded-lg p-3"><h4 className="text-indigo-400 text-xs font-medium mb-1">{t.method}</h4><p className="text-white text-sm">{lang==='ko'?analyzeResult.monetization_method:analyzeResult.monetization_method_en}</p></div>
                  <div className="bg-slate-800/50 rounded-lg p-3"><h4 className="text-indigo-400 text-xs font-medium mb-1">{t.principle}</h4><p className="text-white text-sm">{lang==='ko'?analyzeResult.core_principle:analyzeResult.core_principle_en}</p></div>
                  <div className="bg-slate-800/50 rounded-lg p-3"><h4 className="text-indigo-400 text-xs font-medium mb-1">{t.revenuePotential}</h4><p className="text-white text-sm">{lang==='ko'?analyzeResult.revenue_potential:analyzeResult.revenue_potential_en}</p></div>
                  <div className="bg-slate-800/50 rounded-lg p-3"><h4 className="text-indigo-400 text-xs font-medium mb-1">{t.competition}</h4><p className="text-white text-sm">{lang==='ko'?analyzeResult.competition_level:analyzeResult.competition_level_en}</p></div>
                </div>
                <div><h4 className="text-indigo-400 text-xs font-medium mb-1">{t.requirements}</h4><p className="text-white text-sm">{lang==='ko'?analyzeResult.requirements:analyzeResult.requirements_en}</p></div>
                <div><h4 className="text-indigo-400 text-xs font-medium mb-1">{t.keyInsight}</h4><p className="text-yellow-300 text-sm font-medium">{lang==='ko'?analyzeResult.key_insight:analyzeResult.key_insight_en}</p></div>
                <div className="flex flex-wrap gap-6">
                  <div><span className="text-slate-400 text-xs block mb-1">{t.difficulty}</span><MeterBar value={analyzeResult.difficulty} color="bg-orange-500"/></div>
                  <div><span className="text-slate-400 text-xs block mb-1">{t.cost}</span><MeterBar value={analyzeResult.initial_cost} color="bg-red-500"/></div>
                  <div><span className="text-slate-400 text-xs block mb-1">{t.time}</span><MeterBar value={analyzeResult.time_to_profit} color="bg-yellow-500"/></div>
                </div>
                <p className="text-slate-500 text-[10px] leading-relaxed">{t.analyzeDisclaimer}</p>
              </div>
            )}
          </div>
        </div>

        {/* Navigation tabs - PH style */}
        <div className="flex flex-col lg:flex-row gap-6 items-start w-full overflow-hidden">
          <div className="flex-1 min-w-0 w-full max-w-full overflow-hidden">
            {/* Step 1: Region selection */}
            <div className={`rounded-lg p-3 mb-3 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-white border border-gray-200 shadow-sm'}`}>
              <p className={`text-[11px] mb-2 ${isDark?'text-slate-500':'text-gray-500'}`}>{lang==='ko'?'지역 선택':'Select Region'}</p>
              <div className="flex flex-wrap gap-2">
                <button onClick={()=>setRegion('korea')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${region==='korea'?'bg-blue-600 text-white shadow-md':isDark?'bg-slate-800 text-slate-400 hover:text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{t.regionKr}</button>
                <button onClick={()=>setRegion('global')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${region==='global'?'bg-emerald-600 text-white shadow-md':isDark?'bg-slate-800 text-slate-400 hover:text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{t.regionGlobal}</button>
                <button onClick={()=>setRegion('aitool')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${region==='aitool'?'bg-cyan-600 text-white shadow-md':isDark?'bg-slate-800 text-slate-400 hover:text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{t.regionAitool}</button>
              </div>
            </div>
            {/* Step 2: Content type selection */}
            <div className={`rounded-lg p-3 mb-3 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-white border border-gray-200 shadow-sm'}`}>
              <p className={`text-[11px] mb-2 ${isDark?'text-slate-500':'text-gray-500'}`}>{lang==='ko'?'콘텐츠 유형':'Content Type'}</p>
              <div className="flex flex-wrap gap-2">
                <button onClick={()=>setContentType('shorts')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${contentType==='shorts'?'bg-rose-600 text-white shadow-md':isDark?'bg-slate-800 text-slate-400 hover:text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{t.tabShorts}</button>
                <button onClick={()=>setContentType('videos')} className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${contentType==='videos'?'bg-violet-600 text-white shadow-md':isDark?'bg-slate-800 text-slate-400 hover:text-white':'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}>{t.tabVideos}</button>
              </div>
            </div>

            {/* Period tabs */}
            <div className="flex flex-wrap gap-2 mb-4">
              {['daily','weekly','monthly'].map((p,i)=>(<button key={p} onClick={()=>setPeriod(p)} className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${period===p?'bg-indigo-600 text-white':isDark?'bg-slate-800/80 text-slate-400 hover:text-white':'bg-gray-200 text-gray-600 hover:text-gray-900'}`}>{[t.tabDaily,t.tabWeekly,t.tabMonthly][i]}</button>))}
            </div>

            {/* Category chips */}
            <div className="flex flex-wrap gap-1.5 mb-4">{categoryKeys.map((cat,i)=>(<button key={cat} onClick={()=>setActiveCategory(cat)} className={`px-2.5 py-1 rounded-full text-[11px] transition-all ${activeCategory===cat?'bg-purple-600 text-white':isDark?'bg-slate-800/80 text-slate-400 hover:text-white border border-slate-700/50':'bg-gray-200 text-gray-600 hover:text-gray-900 border border-gray-300'}`}>{categories[i]}</button>))}</div>

            {/* Filter bar - compact */}
            <div className={`rounded-lg p-3 mb-4 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-white border border-gray-200 shadow-sm'}`}>
              <div className="flex items-center justify-between mb-2">
                <h4 className={`text-xs font-medium ${isDark?'text-slate-300':'text-gray-700'}`}>{t.filterTitle}</h4>
                {hasFilters&&(<button onClick={()=>{setFilterDifficulty(null);setFilterCost(null);setFilterTime(null)}} className="text-indigo-400 text-xs hover:text-indigo-300">Reset</button>)}
              </div>
              <p className={`text-[10px] mb-2 ${isDark?'text-slate-600':'text-gray-400'}`}>{t.filterHint}</p>
              <div className="flex flex-wrap gap-4">
                <ClickableMeter label={t.difficulty} value={filterDifficulty} onChange={setFilterDifficulty} color="bg-orange-500"/>
                <ClickableMeter label={t.cost} value={filterCost} onChange={setFilterCost} color="bg-red-500"/>
                <ClickableMeter label={t.time} value={filterTime} onChange={setFilterTime} color="bg-yellow-500"/>
              </div>
            </div>

            {/* Search */}
            <div className="relative mb-4">
              <input type="text" placeholder={t.search} value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} className={`w-full rounded-lg px-4 py-2.5 pl-10 text-sm focus:outline-none focus:border-indigo-500 ${isDark?'bg-slate-900/50 border border-slate-800 text-white placeholder-slate-500':'bg-white border border-gray-200 text-gray-900 placeholder-gray-400 shadow-sm'}`}/>
              <svg className="absolute left-3 top-3 w-4 h-4 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/></svg>
            </div>

            {/* Ranking list - PH style */}
            {items.length===0?(<div className="bg-slate-900/50 border border-slate-800 rounded-xl p-12 text-center"><p className="text-slate-400 text-sm">{t.noData}</p></div>):(
              <div className="space-y-2">
                {items.map((item,index)=>(
                  <React.Fragment key={item.video_id}>
                    {index===3&&bannerAd&&<AdAsRank ad={bannerAd} lang={lang}/>}
                    <RankItem item={item} rank={index+1} lang={lang} t={t} isDark={isDark} isExpanded={expandedId===item.video_id} onToggle={()=>setExpandedId(expandedId===item.video_id?null:item.video_id)} onWatch={setPopupVideoId} ads={adsConfig?.ads||[]}/>
                    {index===6&&inlineAd&&<AdAsRank ad={inlineAd} lang={lang}/>}
                  </React.Fragment>
                ))}
              </div>
            )}
          </div>

          {/* Sidebar */}
          <aside className="w-full lg:w-72 lg:sticky lg:top-16 space-y-3 flex-shrink-0 overflow-hidden">
            {sidebarAds.map(ad=><SidebarAdSlot key={ad.id} ad={ad} lang={lang} t={t}/>)}
            {Array.from({length:Math.max(0,3-sidebarAds.length)},(_,i)=>(<SidebarAdSlot key={`e-${i}`} ad={null} lang={lang} t={t}/>))}
            <div className={`rounded-xl p-4 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-white border border-gray-200 shadow-sm'}`}><h4 className={`font-medium text-sm mb-2 ${isDark?'text-white':'text-gray-900'}`}>{t.aboutTitle}</h4><p className={`text-xs leading-relaxed ${isDark?'text-slate-400':'text-gray-600'}`}>{t.aboutText}</p></div>
            <div className={`rounded-xl p-4 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-white border border-gray-200 shadow-sm'}`}><h4 className={`font-medium text-sm mb-2 ${isDark?'text-white':'text-gray-900'}`}>{t.rankTitle}</h4><ul className={`text-xs space-y-1 ${isDark?'text-slate-400':'text-gray-600'}`}>{t.rankRules.map((r,i)=><li key={i}>• {r}</li>)}</ul></div>
            <div className={`rounded-xl p-4 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-white border border-gray-200 shadow-sm'}`}><h4 className={`font-medium text-sm mb-3 ${isDark?'text-white':'text-gray-900'}`}>Trend Keywords</h4><TrendKeywords data={dailyData}/></div>
          </aside>
        </div>
      </main>

      {/* Footer */}
      <footer className={`border-t mt-12 ${isDark?'border-slate-800/50':'border-gray-200'}`}>
        <div className="max-w-6xl mx-auto px-4 py-8">
          <div className={`rounded-lg p-4 mb-6 ${isDark?'bg-slate-900/50 border border-slate-800':'bg-gray-100 border border-gray-200'}`}><p className={`text-xs leading-relaxed ${isDark?'text-slate-500':'text-gray-600'}`}><span className={`font-medium ${isDark?'text-slate-400':'text-gray-700'}`}>{t.disclaimer}: </span>{t.disclaimerText}</p></div>
          <div className={`flex flex-col md:flex-row items-center justify-between gap-4 text-xs ${isDark?'text-slate-600':'text-gray-500'}`}>
            <p>{t.source}</p><p>{t.masked}</p>
          </div>
          <div className="flex items-center justify-center gap-4 mt-4">
            <button onClick={()=>setShowTerms(true)} className={`text-xs hover:text-indigo-400 ${isDark?'text-slate-500':'text-gray-500'}`}>{t.termsTitle}</button>
            <button onClick={()=>setShowContact(true)} className={`text-xs hover:text-indigo-400 ${isDark?'text-slate-500':'text-gray-500'}`}>{t.contactTitle}</button>
            <button onClick={()=>setShowContact(true)} className={`text-xs hover:text-indigo-400 ${isDark?'text-slate-500':'text-gray-500'}`}>{t.reportBtn}</button>
          </div>
        </div>
      </footer>
    </div>
  )
}
